apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Elasticsearch.v1.logging.openshift.io,Kibana.v1.logging.openshift.io
    operatorframework.io/bundle-unpack-min-retry-interval: 5m
  generateName: openshift-operators-redhat-
  namespace: openshift-operators-redhat
spec: {}
