apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Elasticsearch.v1.logging.openshift.io,Kibana.v1.logging.openshift.io
  generateName: openshift-distributed-tracing-
  namespace: openshift-distributed-tracing
spec: {}
